
country_to_continent_mapping = {
     "afghanistan":  "asia",
     "albania":  "europe",
     "algeria":  "africa",
     "andorra":  "europe",
     "angola":  "africa",
     "anguilla":  "north america",
     "antigua and barbuda":  "north america",
     "argentina":  "south america",
     "armenia":  "asia",
     "australia":  "oceania",
     "austria":  "europe",
     "azerbaijan":  "asia",
     "the bahamas":  "north america",
     "bahrain":  "asia",
     "bangladesh":  "asia",
     "barbados":  "north america",
     "belarus":  "europe",
     "belgium":  "europe",
     "belize":  "north america",
     "benin":  "africa",
     "bhutan":  "asia",
     "bolivia":  "south america",
     "bosnia and herzegovina":  "europe",
     "botswana":  "africa",
     "brazil":  "south america",
     "brunei":  "asia",
     "bulgaria":  "europe",
     "burkina faso":  "africa",
     "burundi":  "africa",
     "cambodia":  "asia",
     "cameroon":  "africa",
     "canada":  "north america",
     "cape verde":  "africa",
     "central african republic":  "africa",
     "chad":  "africa",
     "chile":  "south america",
     "china":  "asia",
     "colombia":  "south america",
     "comoros":  "africa",
     "congo":  "africa",
     "cook islands":  "oceania",
     "costa rica":  "north america",
     "croatia":  "europe",
     "cuba":  "north america",
     "cyprus":  "asia",
     "czech republic":  "europe",
     "denmark":  "europe",
     "djibouti":  "africa",
     "dominica":  "north america",
     "dominican republic":  "north america",
     "east timor":  "asia",
     "ecuador":  "south america",
     "egypt":  "africa",
     "el salvador":  "north america",
     "england":  "europe",
     "equatorial guinea":  "africa",
     "eritrea":  "africa",
     "estonia":  "europe",
     "ethiopia":  "africa",
     "fiji":  "oceania",
     "finland":  "europe",
     "france":  "europe",
     "gabon":  "africa",
     "gambia":  "africa",
     "georgia":  "asia",
     "germany":  "europe",
     "ghana":  "africa",
     "greece":  "europe",
     "grenada":  "north america",
     "guatemala":  "north america",
     "guinea":  "africa",
     "guinea_bissau":  "africa",
     "guyana":  "south america",
     "haiti":  "north america",
     "vatican city":  "europe",
     "honduras":  "north america",
     "hungary":  "europe",
     "iceland":  "europe",
     "india":  "asia",
     "indonesia":  "asia",
     "iran":  "asia",
     "iraq":  "asia",
     "ireland":  "europe",
     "israel":  "asia",
     "italy":  "europe",
     "ivory coast":  "africa",
     "jamaica":  "north america",
     "japan":  "asia",
     "jordan":  "asia",
     "kazakhstan":  "asia",
     "kenya":  "africa",
     "kiribati":  "oceania",
     "kuwait":  "asia",
     "kyrgyzstan":  "asia",
     "laos":  "asia",
     "latvia":  "europe",
     "lebanon":  "asia",
     "lesotho":  "africa",
     "liberia":  "africa",
     "libya":  "africa",
     "liechtenstein":  "europe",
     "lithuania":  "europe",
     "luxembourg":  "europe",
     "north macedonia":  "europe",
     "madagascar":  "africa",
     "malawi":  "africa",
     "malaysia":  "asia",
     "maldives":  "asia",
     "mali":  "africa",
     "malta":  "europe",
     "marshall islands":  "oceania",
     "mauritania":  "africa",
     "mauritius":  "africa",
     "mexico":  "north america",
     "micronesia":  "oceania",
     "moldova":  "europe",
     "monaco":  "europe",
     "mongolia":  "asia",
     "montenegro":  "europe",
     "montserrat":  "north america",
     "morocco":  "africa",
     "mozambique":  "africa",
     "myanmar":  "asia",
     "namibia":  "africa",
     "nauru":  "oceania",
     "nepal":  "asia",
     "netherlands":  "europe",
     "new zealand":  "oceania",
     "nicaragua":  "north america",
     "niger":  "africa",
     "nigeria":  "africa",
     "niue":  "oceania",
     "north korea":  "asia",
     "norway":  "europe",
     "oman":  "asia",
     "pakistan":  "asia",
     "palau":  "oceania",
     "palestine":  "asia",
     "panama":  "north america",
     "papua new guinea":  "oceania",
     "paraguay":  "south america",
     "peru":  "south america",
     "philippines":  "asia",
     "poland":  "europe",
     "portugal":  "europe",
     "qatar":  "asia",
     "romania":  "europe",
     "russia":  "europe",
     "rwanda":  "africa",
     "saint kitts and nevis":  "north america",
     "saint lucia":  "north america",
     "saint vincent and the grenadines":  "north america",
     "samoa":  "oceania",
     "san marino":  "europe",
     "saudi arabia":  "asia",
     "scotland":  "europe",
     "senegal":  "africa",
     "serbia":  "europe",
     "seychelles":  "africa",
     "sierra leone":  "africa",
     "singapore":  "asia",
     "slovakia":  "europe",
     "slovenia":  "europe",
     "solomon islands":  "oceania",
     "somalia":  "africa",
     "south africa":  "africa",
     "south korea":  "asia",
     "south sudan":  "africa",
     "spain":  "europe",
     "sri lanka":  "asia",
     "sudan":  "africa",
     "suriname":  "south america",
     "swaziland":  "africa",
     "sweden":  "europe",
     "switzerland":  "europe",
     "syria":  "asia",
     "tajikistan":  "asia",
     "tanzania":  "africa",
     "thailand":  "asia",
     "congo":  "africa",
     "togo":  "africa",
     "tokelau":  "oceania",
     "tonga":  "oceania",
     "trinidad and tobago":  "north america",
     "tunisia":  "africa",
     "turkey":  "asia",
     "turkmenistan":  "asia",
     "turks and caicos islands":  "north america",
     "tuvalu":  "oceania",
     "uganda":  "africa",
     "ukraine":  "europe",
     "united arab emirates":  "asia",
     "united kingdom":  "europe",
     "united states":  "north america",
     "uruguay":  "south america",
     "uzbekistan":  "asia",
     "vanuatu":  "oceania",
     "venezuela":  "south america",
     "vietnam":  "asia",
     "virgin islands":  "north america",
     "wales":  "europe",
     "yemen":  "asia",
     "zambia":  "africa",
     "zimbabwe":  "africa"
}


if __name__ == "__main__":
     print(f'We have {len(country_to_continent_mapping)} countries')